name: Node.js CI

on:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
          make install
      env:
          CI: true
    - name: Run linter
      run: |
          make lint
    - name: Run test
      run: |
          make test